# Generated by Django 4.2.7 on 2024-10-10 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_first_name_alter_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='profilepic.jpg', null=True, upload_to='profile_pictures'),
        ),
    ]
